/* onramp-session.js — LE RAIL FIAT -> BASE, ECRIT EN ENTIER, EN ECHEC FERME.
 *
 * ⛔⛔ POURQUOI CE MODULE EXISTE. Phil, 2026-09-23 : « la raison [d echanger chez nous] est le
 *     bridge fiat to block, les fonds via Visa Coinbase Onramp ». Aujourd hui l app ne fait PAS
 *     ca : elle pose un lien vers `https://www.coinbase.com/onramp`, la page d accueil publique —
 *     sans adresse de destination, sans montant, sans reseau. Ce n est pas un rail, c est un lien.
 *
 * ⛔⛔ CE QUE LA DOC DIT, LU A LA SOURCE LE 2026-09-23
 *     (docs.cdp.coinbase.com, « Generating an Onramp URL ») :
 *         sessionToken   Required: Yes   « Token generated by the Onramp Session Token API »
 *         defaultNetwork, defaultAsset, presetFiatAmount, redirectUrl, partnerUserRef : facultatifs
 *     Et le token se cree « in your backend », avec un JWT signe par une cle secrete CDP.
 *     ⇒ L ADRESSE DE DESTINATION N EST PAS UN PARAMETRE D URL : elle se fixe a la creation de la
 *       session, cote serveur. Il n existe donc AUCUN moyen d envoyer les fonds au bon wallet sans
 *       cette cle. Le rail entier depend d un geste de Phil.
 *
 * ⛔ CE MODULE NE SIMULE RIEN. Sans cle, il REFUSE en nommant ce qui manque. Fabriquer une URL
 *    plausible ferait un bouton qui envoie les gens sur une page d erreur Coinbase — pire que pas
 *    de bouton du tout.
 * ⛔ IL NE TOUCHE JAMAIS AU SECRET : il lit sa PRESENCE dans l environnement, ne le renvoie
 *    jamais, ne le journalise jamais, et aucune de ses sorties ne le contient.
 * ⚠️ CE QUI N A PAS PU ETRE EXERCE : l appel reseau a Coinbase et la signature du JWT. Ils sont
 *    ecrits, ils ne sont pas PROUVES — aucune cle n existe ici. Les parties PURES (validation,
 *    construction d URL, etat) sont testees, elles.
 */

/** Les noms d environnement que CDP documente. On accepte les deux graphies rencontrees. */
const NOMS_CLE = ['CDP_API_KEY_ID', 'CDP_API_KEY_NAME'];
const NOMS_SECRET = ['CDP_API_KEY_SECRET', 'CDP_API_KEY_PRIVATE_KEY'];

/**
 * L etat du rail, SANS jamais rendre le secret.
 * ⛔ TROIS ETATS, JAMAIS DEUX : pret · cle absente · secret absent. « pas configure » en bloc
 *    empecherait de savoir LEQUEL des deux manque, et on chercherait a l aveugle.
 */
export function etatCdp(env = {}) {
  const cle = NOMS_CLE.find((n) => typeof env[n] === 'string' && env[n].trim().length > 0) || null;
  const sec = NOMS_SECRET.find((n) => typeof env[n] === 'string' && env[n].trim().length > 0) || null;
  if (cle && sec) return { pret: true, cle, secret: sec, pourquoi: null };
  if (!cle && !sec) {
    return { pret: false, cle: null, secret: null,
      pourquoi: 'no CDP credentials: set ' + NOMS_CLE[0] + ' and ' + NOMS_SECRET[0] };
  }
  if (!cle) return { pret: false, cle: null, secret: sec, pourquoi: 'CDP key id missing (' + NOMS_CLE[0] + ')' };
  return { pret: false, cle, secret: null, pourquoi: 'CDP key secret missing (' + NOMS_SECRET[0] + ')' };
}

const ADR = /^0x[0-9a-fA-F]{40}$/;
/* ⛔ Coinbase nomme le reseau Base « base ». On ne propose QUE lui : un autre reseau enverrait les
 *   fonds sur une chaine ou les blocks n existent pas. */
export const RESEAU_ONRAMP = 'base';
/* ⛔ Les deux seuls actifs que nos chemins savent consommer : l ETH paie la naissance, l USDC paie
 *   les messages et le Bridge. Proposer un autre actif enverrait de l argent qu on ne sait pas
 *   depenser. */
export const ACTIFS_ONRAMP = Object.freeze(['ETH', 'USDC']);
/* ⛔ Bornes du montant. Le plancher vient du frais de naissance (0,001 ETH, quelques dollars) ; le
 *   plafond evite qu une faute de frappe envoie un montant qu on n a jamais teste. Ce sont des
 *   bornes de PRUDENCE, pas une limite de Coinbase — et c est dit. */
export const FIAT_MIN = 2, FIAT_MAX = 500;

/**
 * Valide une demande de session. PUR : aucune lecture reseau, aucun secret.
 * ⛔ FAIL-CLOSED SUR CHAQUE CHAMP, avec une raison NOMMEE : « invalide » tout court enverrait
 *    l utilisateur recommencer sans savoir quoi corriger.
 */
export function validerDemande(d) {
  const o = d || {};
  if (!ADR.test(String(o.adresse || ''))) {
    return { etat: 'REFUSE', pourquoi: 'a whole wallet address is required — funds must land somewhere real' };
  }
  /* ⛔⛔ ABSENT ET VIDE NE SONT PAS LA MEME CHOSE, et ma premiere version les confondait :
   *     `String(o.actif || 'ETH')` transformait `''` en ETH. Un champ ABSENT veut dire « pas de
   *     preference » et prend le defaut ; un champ PRESENT ET VIDE veut dire que l appelant avait
   *     un selecteur d actif et qu il est revenu blanc — un defaut chez lui. Le masquer par un
   *     defaut ferait acheter de l ETH a quelqu un qui n a rien choisi. C est le meme piege que
   *     `Number('') === 0` juste en dessous, et il faut la meme reponse. */
  const actifBrut = o.actif;
  const actif = (actifBrut === undefined || actifBrut === null) ? 'ETH' : String(actifBrut).toUpperCase();
  if (!ACTIFS_ONRAMP.includes(actif)) {
    return { etat: 'REFUSE', pourquoi: 'asset must be one of ' + ACTIFS_ONRAMP.join(', ') };
  }
  /* ⛔⛔ LE MONTANT EST FACULTATIF, ET MA PREMIERE VERSION LE RENDAIT OBLIGATOIRE. Ca a tue le rail
   *     ENTIER pendant une journee, en production : le seul appelant (`ouvrirRailFiat` dans
   *     app.html) n envoie pas de montant, donc la route rendait 400 a CHAQUE clic, donc le client
   *     retombait toujours sur le lien public. Le bouton avait l air de marcher — il ne faisait
   *     rien de ce pour quoi il avait ete ecrit.
   *     ⛔ Et ma verification d hier n a pas vu le defaut parce qu elle regardait le COMPTEUR
   *       d entonnoir monter. Or le chemin de REPLI incremente lui aussi (`onramp_session_repli`) :
   *       j ai mesure que l ecouteur partait, pas que le rail aboutissait.
   *     ⇒ La doc CDP est claire : `presetFiatAmount` est FACULTATIF. Exiger le montant etait ma
   *       decision, pas la leur, et elle rendait la route inatteignable. Coinbase demande le
   *       montant sur son propre ecran ; le pre-remplir est un confort, jamais une condition.
   *
   * ⛔ ABSENT et VIDE restent distincts, comme pour l actif juste au-dessus. `URLSearchParams.get`
   *   rend `null` quand le parametre MANQUE (pas de preference : on accepte) et `''` quand il est
   *   present mais blanc (un champ soumis vide : defaut de l appelant, on refuse). Et on refuse
   *   AVANT de convertir, sinon `Number('')` vaudrait 0 et un champ vide passerait pour « zero
   *   dollar » — le meme piege que la pool « gratuite » au classement des frais. */
  /* ⛔⛔ LE BLOCK DE RETOUR — ET C EST UN PARAMETRE DE REDIRECTION, DONC ON LE TRAITE COMME TEL.
   *     Mesure du 2026-09-27 : `retour` etait code en dur sur la page d accueil. Quelqu un qui
   *     finance depuis l ecran d un block revient donc SUR RIEN et doit le retrouver a la main.
   *     L intention (`poserIntent`) ne peut pas l aider : elle vit en `sessionStorage`, et l onramp
   *     s ouvre dans un NOUVEL onglet `noopener`, dont le stockage est vierge. Le seul support qui
   *     traverse un aller-retour inter-onglets est l URL elle-meme.
   *   ⛔⛔ ON NE REFLECHIT JAMAIS UN HOTE FOURNI PAR L APPELANT. Le domaine de retour reste decide
   *       par le serveur ; on n accepte ici qu une ADRESSE DE BLOCK, validee par la meme regle que
   *       partout ailleurs. Accepter une url de retour serait une porte d open-redirect sur un
   *       ecran qui parle d argent — precisement l endroit ou on n en veut pas.
   *   ⛔ ABSENT et VIDE restent distincts, comme au-dessus. */
  const blocBrut = o.retourBlock;
  let retourBlock = null;
  if (blocBrut !== null && blocBrut !== undefined) {
    if (!ADR.test(String(blocBrut))) {
      return { etat: 'REFUSE', pourquoi: 'return block was sent but is not a whole address' };
    }
    retourBlock = String(blocBrut).toLowerCase();
  }
  const brut = o.montantFiat;
  if (brut === null || brut === undefined) {
    return { etat: 'OK', adresse: String(o.adresse).toLowerCase(), actif, montantFiat: null, retourBlock };
  }
  if (brut === '') return { etat: 'REFUSE', pourquoi: 'fiat amount was sent but left blank' };
  const montant = Number(brut);
  if (!Number.isFinite(montant)) return { etat: 'REFUSE', pourquoi: 'fiat amount is not a number' };
  if (montant < FIAT_MIN || montant > FIAT_MAX) {
    return { etat: 'REFUSE',
      pourquoi: 'fiat amount must be between ' + FIAT_MIN + ' and ' + FIAT_MAX + ' (our own caution bound, not a Coinbase limit)' };
  }
  return { etat: 'OK', adresse: String(o.adresse).toLowerCase(), actif, montantFiat: montant, retourBlock };
}

/**
 * L URL one-click, a partir d un jeton de session DEJA obtenu.
 * ⛔ LE JETON EST OBLIGATOIRE ET N EST JAMAIS INVENTE : sans lui, Coinbase rend une page d erreur.
 *    Un bouton qui mene a une erreur est pire que pas de bouton.
 */
export function urlOnramp({ sessionToken, actif = 'ETH', montantFiat = null, retour = null } = {}) {
  if (typeof sessionToken !== 'string' || !sessionToken.trim()) {
    return { etat: 'REFUSE', pourquoi: 'no session token — the fiat rail cannot be built without one' };
  }
  const p = new URLSearchParams();
  p.set('sessionToken', sessionToken.trim());
  p.set('defaultNetwork', RESEAU_ONRAMP);
  if (ACTIFS_ONRAMP.includes(String(actif).toUpperCase())) p.set('defaultAsset', String(actif).toUpperCase());
  if (Number.isFinite(Number(montantFiat)) && Number(montantFiat) > 0) {
    p.set('presetFiatAmount', String(Number(montantFiat)));
  }
  /* ⛔ `redirectUrl` n est pose QUE sur https : la doc exige une liste blanche de domaines, et une
   *   url non https serait refusee par Coinbase — ou, pire, acceptee et ouverte en clair. */
  if (typeof retour === 'string' && /^https:\/\/[^\s]+$/i.test(retour)) p.set('redirectUrl', retour);
  return { etat: 'OK', url: 'https://pay.coinbase.com/buy/select-asset?' + p.toString() };
}

/**
 * Cree la session chez Coinbase. ECRIT, PAS PROUVE : aucune cle n existe ici pour l exercer.
 * ⛔ Le secret ne sort jamais de cette fonction, et aucune de ses erreurs ne le contient.
 */
export async function creerSession({ env = {}, adresse, actif = 'ETH', fetchImpl = null } = {}) {
  const etat = etatCdp(env);
  if (!etat.pret) return { etat: 'NON_CONFIGURE', pourquoi: etat.pourquoi };
  if (!ADR.test(String(adresse || ''))) return { etat: 'REFUSE', pourquoi: 'a whole wallet address is required' };
  const f = fetchImpl || (typeof fetch === 'function' ? fetch : null);
  if (!f) return { etat: 'NON_MESURE', pourquoi: 'no fetch available in this runtime' };
  /* ⛔ LE JWT EST SIGNE PAR L APPELANT, jamais ici : ce module ne manipule pas le secret. Le
   *   serveur le passe deja signe. Melanger signature et transport mettrait la cle sur le chemin
   *   de chaque erreur journalisee. */
  const jwt = typeof env.__CDP_JWT === 'string' ? env.__CDP_JWT : null;
  if (!jwt) return { etat: 'NON_CONFIGURE', pourquoi: 'no signed CDP JWT was provided to this call' };
  try {
    const r = await f('https://api.developer.coinbase.com/onramp/v1/token', {
      method: 'POST',
      headers: { 'content-type': 'application/json', authorization: 'Bearer ' + jwt },
      body: JSON.stringify({ addresses: [{ address: String(adresse), blockchains: [RESEAU_ONRAMP] }],
        assets: [String(actif).toUpperCase()] }),
    });
    if (!r.ok) return { etat: 'REFUSE_PAR_COINBASE', pourquoi: 'Coinbase answered HTTP ' + r.status };
    const j = await r.json().catch(() => null);
    const jeton = j && (j.token || j.sessionToken || (j.data && j.data.token));
    if (typeof jeton !== 'string' || !jeton) {
      return { etat: 'ILLISIBLE', pourquoi: 'Coinbase answered without a session token' };
    }
    return { etat: 'OK', sessionToken: jeton };
  } catch (e) {
    /* ⛔ le message d erreur est TRONQUE et ne peut pas porter le secret : il ne transite pas ici. */
    return { etat: 'NON_MESURE', pourquoi: 'session call failed: ' + String((e && e.message) || e).slice(0, 120) };
  }
}

/** Le CHEMIN CDP du catalogue d achat. Sorti en constante parce que le JWT le signe : une
 *  divergence entre le chemin signe et le chemin appele rend un 401 muet, et on chercherait le
 *  defaut dans la cle. Voir `cdp-jwt.js` — `uri` = METHODE + hote + chemin. */
export const CHEMIN_OPTIONS_ACHAT = '/onramp/v1/buy/options';

/**
 * Demande a Coinbase CE QU IL SAIT VENDRE, et sur quels reseaux.
 *
 * ⛔⛔ POURQUOI CETTE ROUTE EXISTE (Phil, 2026-09-27) : « le rail doit se faire fiat onramp Coinbase
 *     puis Block tokenise OU ACTION TOKENISEE direct ». La question ne se tranche pas par
 *     raisonnement — elle se demande a Coinbase. Trois chemins avaient echoue avant celui-ci : la
 *     page d achat exige une connexion au compte (refusee), `buy/options` rend 401 sans JWT, et
 *     `pay.coinbase.com/api/v1/buy/options` exige un app-id absent du depot.
 *
 * ⛔ CE MODULE NE MANIPULE PAS LE SECRET. Le JWT arrive deja signe, comme pour `creerSession` : la
 *   cle ne doit jamais se trouver sur le chemin d une erreur journalisee.
 * ⛔ ET LA QUERY N EST PAS DANS LE JWT. `uri` ne signe que METHODE + hote + CHEMIN ; ajouter le
 *   `?country=` a la chaine signee produirait un 401 que rien n expliquerait.
 *
 * ⚠️ CE QU ELLE NE PROUVE PAS : qu un achat aboutisse. Elle dit ce que le catalogue CONTIENT.
 * @returns {Promise<{etat:string, actifs?:object[], pourquoi?:string}>}
 */
export async function lireOptionsAchat({ env = {}, pays = 'US', subdivision = null, fetchImpl = null } = {}) {
  const etat = etatCdp(env);
  if (!etat.pret) return { etat: 'NON_CONFIGURE', pourquoi: etat.pourquoi };
  /* ⛔ LE PAYS EST BORNE A DEUX LETTRES : il part dans une URL vers un tiers, et tout ce qui vient
   *   de l appelant et voyage doit etre contraint avant, pas apres. */
  const p = String(pays || '').toUpperCase();
  if (!/^[A-Z]{2}$/.test(p)) return { etat: 'REFUSE', pourquoi: 'country must be a 2-letter code' };
  const sub = subdivision === null || subdivision === undefined ? null : String(subdivision).toUpperCase();
  if (sub !== null && !/^[A-Z]{2}$/.test(sub)) {
    return { etat: 'REFUSE', pourquoi: 'subdivision must be a 2-letter code when present' };
  }
  const f = fetchImpl || (typeof fetch === 'function' ? fetch : null);
  if (!f) return { etat: 'NON_MESURE', pourquoi: 'no fetch available in this runtime' };
  const jwt = typeof env.__CDP_JWT === 'string' ? env.__CDP_JWT : null;
  if (!jwt) return { etat: 'NON_CONFIGURE', pourquoi: 'no signed CDP JWT was provided to this call' };
  const q = '?country=' + encodeURIComponent(p) + (sub ? '&subdivision=' + encodeURIComponent(sub) : '');
  try {
    const r = await f('https://api.developer.coinbase.com' + CHEMIN_OPTIONS_ACHAT + q, {
      method: 'GET', headers: { authorization: 'Bearer ' + jwt },
    });
    if (!r.ok) return { etat: 'REFUSE_PAR_COINBASE', pourquoi: 'Coinbase answered HTTP ' + r.status };
    const j = await r.json().catch(() => null);
    const brut = (j && (j.purchase_currencies || j.purchaseCurrencies)) || null;
    if (!Array.isArray(brut)) return { etat: 'ILLISIBLE', pourquoi: 'Coinbase answered without a purchase list' };
    /* ⛔ ON NE REND QUE CE QU ON A LU, et on garde les reseaux : « vendable » sans « sur quel
     *   reseau » ne repond pas a la question posee — un actif vendable sur Ethereum seulement ne
     *   sert a rien a un block sur Base. */
    const actifs = brut.map((c) => ({
      symbole: String((c && (c.symbol || c.id)) || '').toUpperCase().slice(0, 16),
      nom: String((c && c.name) || '').slice(0, 40),
      reseaux: Array.isArray(c && c.networks)
        ? c.networks.map((n) => String((n && (n.name || n.display_name || n)) || '').toLowerCase().slice(0, 24))
        : [],
    })).filter((a) => a.symbole);

    /* ⛔⛔ LES DEVISES FIAT ETAIENT LUES PUIS JETEES, ET C ETAIT UN DEFAUT. Coinbase rend DEUX listes
     *     dans cette MEME reponse : `purchase_currencies` (ce qu on achete) et `payment_currencies`
     *     (ce avec quoi on paie). On ne gardait que la premiere.
     *     Consequence mesuree le 2026-09-28 : impossible de repondre a « avec combien de DEVISES ce
     *     chemin marche-t-il ? » autrement qu en comptant des PAYS — 51 sondes, 51 servis, dont 50
     *     avec USDC sur Base (⛔ le Japon n a AUCUN USDC dans sa liste). Or compter des pays pour
     *     parler de devises repond a cote : vingt pays partagent l euro.
     *   ⛔ UNE VALEUR LUE PUIS JETEE EST UN DEFAUT. La reponse la portait ; il suffisait de la garder.
     *   ⚠️ ET LE NOM DIT SA BORNE : `fiatsDeclares`, pas `fiatsDisponibles`. Cette liste dit ce que
     *     Coinbase DECLARE accepter pour ce pays — restent les moyens de paiement, les limites et la
     *     conformite. Un nom qui promet plus que la mesure est un mensonge a retardement. */
    const brutFiat = (j && (j.payment_currencies || j.paymentCurrencies)) || null;
    const fiatsDeclares = Array.isArray(brutFiat)
      ? [...new Set(brutFiat.map((c) => String((c && (c.id || c.symbol)) || '').toUpperCase().slice(0, 8))
        .filter((s) => /^[A-Z]{3}$/.test(s)))]
      : null;
    /* ⛔ `null` ET PAS `[]` QUAND LA LISTE MANQUE : un tableau vide dirait « aucune devise », un
     *   `null` dit « Coinbase ne l a pas rendue ». Deux faits opposes, et le second est notre
     *   ignorance — les confondre ferait publier « 0 devise » sur une panne de lecture. */
    return { etat: 'OK', actifs, fiatsDeclares, pays: p };
  } catch (e) {
    return { etat: 'NON_MESURE', pourquoi: 'options call failed: ' + String((e && e.message) || e).slice(0, 120) };
  }
}
