/* onramp-session.js — LE RAIL FIAT -> BASE, ECRIT EN ENTIER, EN ECHEC FERME.
 *
 * ⛔⛔ POURQUOI CE MODULE EXISTE. Phil, 2026-09-23 : « la raison [d echanger chez nous] est le
 *     bridge fiat to block, les fonds via Visa Coinbase Onramp ». Aujourd hui l app ne fait PAS
 *     ca : elle pose un lien vers `https://www.coinbase.com/onramp`, la page d accueil publique —
 *     sans adresse de destination, sans montant, sans reseau. Ce n est pas un rail, c est un lien.
 *
 * ⛔⛔ CE QUE LA DOC DIT, LU A LA SOURCE LE 2026-09-23
 *     (docs.cdp.coinbase.com, « Generating an Onramp URL ») :
 *         sessionToken   Required: Yes   « Token generated by the Onramp Session Token API »
 *         defaultNetwork, defaultAsset, presetFiatAmount, redirectUrl, partnerUserRef : facultatifs
 *     Et le token se cree « in your backend », avec un JWT signe par une cle secrete CDP.
 *     ⇒ L ADRESSE DE DESTINATION N EST PAS UN PARAMETRE D URL : elle se fixe a la creation de la
 *       session, cote serveur. Il n existe donc AUCUN moyen d envoyer les fonds au bon wallet sans
 *       cette cle. Le rail entier depend d un geste de Phil.
 *
 * ⛔ CE MODULE NE SIMULE RIEN. Sans cle, il REFUSE en nommant ce qui manque. Fabriquer une URL
 *    plausible ferait un bouton qui envoie les gens sur une page d erreur Coinbase — pire que pas
 *    de bouton du tout.
 * ⛔ IL NE TOUCHE JAMAIS AU SECRET : il lit sa PRESENCE dans l environnement, ne le renvoie
 *    jamais, ne le journalise jamais, et aucune de ses sorties ne le contient.
 * ⚠️ CE QUI N A PAS PU ETRE EXERCE : l appel reseau a Coinbase et la signature du JWT. Ils sont
 *    ecrits, ils ne sont pas PROUVES — aucune cle n existe ici. Les parties PURES (validation,
 *    construction d URL, etat) sont testees, elles.
 */

/** Les noms d environnement que CDP documente. On accepte les deux graphies rencontrees. */
const NOMS_CLE = ['CDP_API_KEY_ID', 'CDP_API_KEY_NAME'];
const NOMS_SECRET = ['CDP_API_KEY_SECRET', 'CDP_API_KEY_PRIVATE_KEY'];

/**
 * L etat du rail, SANS jamais rendre le secret.
 * ⛔ TROIS ETATS, JAMAIS DEUX : pret · cle absente · secret absent. « pas configure » en bloc
 *    empecherait de savoir LEQUEL des deux manque, et on chercherait a l aveugle.
 */
export function etatCdp(env = {}) {
  const cle = NOMS_CLE.find((n) => typeof env[n] === 'string' && env[n].trim().length > 0) || null;
  const sec = NOMS_SECRET.find((n) => typeof env[n] === 'string' && env[n].trim().length > 0) || null;
  if (cle && sec) return { pret: true, cle, secret: sec, pourquoi: null };
  if (!cle && !sec) {
    return { pret: false, cle: null, secret: null,
      pourquoi: 'no CDP credentials: set ' + NOMS_CLE[0] + ' and ' + NOMS_SECRET[0] };
  }
  if (!cle) return { pret: false, cle: null, secret: sec, pourquoi: 'CDP key id missing (' + NOMS_CLE[0] + ')' };
  return { pret: false, cle, secret: null, pourquoi: 'CDP key secret missing (' + NOMS_SECRET[0] + ')' };
}

const ADR = /^0x[0-9a-fA-F]{40}$/;
/* ⛔ Coinbase nomme le reseau Base « base ». On ne propose QUE lui : un autre reseau enverrait les
 *   fonds sur une chaine ou les blocks n existent pas. */
export const RESEAU_ONRAMP = 'base';
/* ⛔ Les deux seuls actifs que nos chemins savent consommer : l ETH paie la naissance, l USDC paie
 *   les messages et le Bridge. Proposer un autre actif enverrait de l argent qu on ne sait pas
 *   depenser. */
export const ACTIFS_ONRAMP = Object.freeze(['ETH', 'USDC']);
/* ⛔ Bornes du montant. Le plancher vient du frais de naissance (0,001 ETH, quelques dollars) ; le
 *   plafond evite qu une faute de frappe envoie un montant qu on n a jamais teste. Ce sont des
 *   bornes de PRUDENCE, pas une limite de Coinbase — et c est dit. */
export const FIAT_MIN = 2, FIAT_MAX = 500;

/**
 * Valide une demande de session. PUR : aucune lecture reseau, aucun secret.
 * ⛔ FAIL-CLOSED SUR CHAQUE CHAMP, avec une raison NOMMEE : « invalide » tout court enverrait
 *    l utilisateur recommencer sans savoir quoi corriger.
 */
export function validerDemande(d) {
  const o = d || {};
  if (!ADR.test(String(o.adresse || ''))) {
    return { etat: 'REFUSE', pourquoi: 'a whole wallet address is required — funds must land somewhere real' };
  }
  /* ⛔⛔ ABSENT ET VIDE NE SONT PAS LA MEME CHOSE, et ma premiere version les confondait :
   *     `String(o.actif || 'ETH')` transformait `''` en ETH. Un champ ABSENT veut dire « pas de
   *     preference » et prend le defaut ; un champ PRESENT ET VIDE veut dire que l appelant avait
   *     un selecteur d actif et qu il est revenu blanc — un defaut chez lui. Le masquer par un
   *     defaut ferait acheter de l ETH a quelqu un qui n a rien choisi. C est le meme piege que
   *     `Number('') === 0` juste en dessous, et il faut la meme reponse. */
  const actifBrut = o.actif;
  const actif = (actifBrut === undefined || actifBrut === null) ? 'ETH' : String(actifBrut).toUpperCase();
  if (!ACTIFS_ONRAMP.includes(actif)) {
    return { etat: 'REFUSE', pourquoi: 'asset must be one of ' + ACTIFS_ONRAMP.join(', ') };
  }
  /* ⛔ `Number(null)` vaut 0 et `Number('')` aussi : on refuse les valeurs vides AVANT de
   *   convertir, sinon un champ non rempli passerait pour un montant de zero — le meme piege qui
   *   avait fait gagner une pool « gratuite » au classement des frais. */
  const brut = o.montantFiat;
  if (brut === null || brut === undefined || brut === '') {
    return { etat: 'REFUSE', pourquoi: 'a fiat amount is required' };
  }
  const montant = Number(brut);
  if (!Number.isFinite(montant)) return { etat: 'REFUSE', pourquoi: 'fiat amount is not a number' };
  if (montant < FIAT_MIN || montant > FIAT_MAX) {
    return { etat: 'REFUSE',
      pourquoi: 'fiat amount must be between ' + FIAT_MIN + ' and ' + FIAT_MAX + ' (our own caution bound, not a Coinbase limit)' };
  }
  return { etat: 'OK', adresse: String(o.adresse).toLowerCase(), actif, montantFiat: montant };
}

/**
 * L URL one-click, a partir d un jeton de session DEJA obtenu.
 * ⛔ LE JETON EST OBLIGATOIRE ET N EST JAMAIS INVENTE : sans lui, Coinbase rend une page d erreur.
 *    Un bouton qui mene a une erreur est pire que pas de bouton.
 */
export function urlOnramp({ sessionToken, actif = 'ETH', montantFiat = null, retour = null } = {}) {
  if (typeof sessionToken !== 'string' || !sessionToken.trim()) {
    return { etat: 'REFUSE', pourquoi: 'no session token — the fiat rail cannot be built without one' };
  }
  const p = new URLSearchParams();
  p.set('sessionToken', sessionToken.trim());
  p.set('defaultNetwork', RESEAU_ONRAMP);
  if (ACTIFS_ONRAMP.includes(String(actif).toUpperCase())) p.set('defaultAsset', String(actif).toUpperCase());
  if (Number.isFinite(Number(montantFiat)) && Number(montantFiat) > 0) {
    p.set('presetFiatAmount', String(Number(montantFiat)));
  }
  /* ⛔ `redirectUrl` n est pose QUE sur https : la doc exige une liste blanche de domaines, et une
   *   url non https serait refusee par Coinbase — ou, pire, acceptee et ouverte en clair. */
  if (typeof retour === 'string' && /^https:\/\/[^\s]+$/i.test(retour)) p.set('redirectUrl', retour);
  return { etat: 'OK', url: 'https://pay.coinbase.com/buy/select-asset?' + p.toString() };
}

/**
 * Cree la session chez Coinbase. ECRIT, PAS PROUVE : aucune cle n existe ici pour l exercer.
 * ⛔ Le secret ne sort jamais de cette fonction, et aucune de ses erreurs ne le contient.
 */
export async function creerSession({ env = {}, adresse, actif = 'ETH', fetchImpl = null } = {}) {
  const etat = etatCdp(env);
  if (!etat.pret) return { etat: 'NON_CONFIGURE', pourquoi: etat.pourquoi };
  if (!ADR.test(String(adresse || ''))) return { etat: 'REFUSE', pourquoi: 'a whole wallet address is required' };
  const f = fetchImpl || (typeof fetch === 'function' ? fetch : null);
  if (!f) return { etat: 'NON_MESURE', pourquoi: 'no fetch available in this runtime' };
  /* ⛔ LE JWT EST SIGNE PAR L APPELANT, jamais ici : ce module ne manipule pas le secret. Le
   *   serveur le passe deja signe. Melanger signature et transport mettrait la cle sur le chemin
   *   de chaque erreur journalisee. */
  const jwt = typeof env.__CDP_JWT === 'string' ? env.__CDP_JWT : null;
  if (!jwt) return { etat: 'NON_CONFIGURE', pourquoi: 'no signed CDP JWT was provided to this call' };
  try {
    const r = await f('https://api.developer.coinbase.com/onramp/v1/token', {
      method: 'POST',
      headers: { 'content-type': 'application/json', authorization: 'Bearer ' + jwt },
      body: JSON.stringify({ addresses: [{ address: String(adresse), blockchains: [RESEAU_ONRAMP] }],
        assets: [String(actif).toUpperCase()] }),
    });
    if (!r.ok) return { etat: 'REFUSE_PAR_COINBASE', pourquoi: 'Coinbase answered HTTP ' + r.status };
    const j = await r.json().catch(() => null);
    const jeton = j && (j.token || j.sessionToken || (j.data && j.data.token));
    if (typeof jeton !== 'string' || !jeton) {
      return { etat: 'ILLISIBLE', pourquoi: 'Coinbase answered without a session token' };
    }
    return { etat: 'OK', sessionToken: jeton };
  } catch (e) {
    /* ⛔ le message d erreur est TRONQUE et ne peut pas porter le secret : il ne transite pas ici. */
    return { etat: 'NON_MESURE', pourquoi: 'session call failed: ' + String((e && e.message) || e).slice(0, 120) };
  }
}
