// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {V9Devises} from "./V9Devises.sol";

/// @notice The quote list of the 0.07 % / 0.03 % hook ("7030") = 62 + ETH, FIXED at construction (no owner, no setter):
///         the V9 19, the 18 Coinbase stocks of 2026-10-02 (0ea4661), then GMEc, HTZc, PFEc, PMc (the a54ced1 list and
///         order; GMEc IN: Phil GO 2026-10-02 23:02), then the 21 other stocks the issuer declares (2026-10-03, founder:
///         « la plus large »). Each currency carries an immutable caution floor (~$1 raw), `planchers()`.
/// @dev The c-stocks: api.coinbase.com/v1/tokenized-stocks (issuer list: 58 tokens on 2026-10-03) and on chain (B20
///      precompile code 0xef, 8 decimals, symbol() == the issuer's symbol — each of the 21 read on Base mainnet that day;
///      SOUNc minted (843 units), the 20 others created with supply 0: admitted NOW because the list can never change).
///      WHY A FIXED LIST and not "any genuine Coinbase stock": every B20 attribute readable on chain (roles, policy IDs,
///      name/symbol/decimals, contractURI, variant) is chosen by whoever calls B20Factory.createB20, and initCalls
///      bypass role gates, so a fake "NFLXc" can copy them all; no robust permissionless check exists.
///      FLOORS: generated by script/planchers-caution.mjs at Base block 52090382 (plan/PLANCHERS-CAUTION.md):
///      POOL = ceil($1 / on-chain pool price); REFERENCE = no readable on-chain pool price, ceil($1 / lower of two
///      agreeing off-chain references), flagged for decision. The 21 have no pool (pool: null in the sources): REFERENCE
///      from Yahoo + Nasdaq read 2026-10-03 (both agree to the cent for all 21). `check --block 52090382` must report
///      ALL 63 MATCH (ETH + 62).
library Devises7030 {
    address internal constant AMDc = 0xB2000000000000000000000d8Ce462E99ee7A47B;
    address internal constant ASTSc = 0xB200000000000000000000B1a29cF17A1819288a;
    address internal constant CAKEc = 0xb200000000000000000000f215E4C890CFb7176B;
    address internal constant DJTc = 0xb200000000000000000000428E3a3eebBb20692B;
    address internal constant DUOLc = 0xb200000000000000000000A613D12dEAfBBb1Db7;
    address internal constant LLYc = 0xB200000000000000000000f1a0F91e34892E4718;
    address internal constant MRNAc = 0xB200000000000000000000e215e9B76ecBA02468;
    address internal constant MRVLc = 0xB200000000000000000000eC3c4c7395Cc609813;
    address internal constant NFLXc = 0xb20000000000000000000058B8c947e44011dFE6;
    address internal constant NVAXc = 0xB200000000000000000000C597c476FCf9Aed3a8;
    address internal constant ORCLc = 0xb200000000000000000000347AFbA223D7B6b63C;
    address internal constant PTONc = 0xB2000000000000000000009272A491812842Aa84;
    address internal constant PYPLc = 0xb200000000000000000000450ad3abE5d4846c6E;
    address internal constant QUBTc = 0xb200000000000000000000CA425ab42e07C35bC3;
    address internal constant RBLXc = 0xB2000000000000000000005bd7AE89b9E6189Bb5;
    address internal constant RDDTc = 0xb20000000000000000000066242d4067724cB7A1;
    address internal constant TTWOc = 0xB200000000000000000000f720C26062Bc3067Da;
    address internal constant WENc = 0xB20000000000000000000044E3CD7a0E1028E57a;
    address internal constant GMEc = 0xb2000000000000000000007790ed6E48e06eD935;
    address internal constant HTZc = 0xb2000000000000000000002601C5C94F435da168;
    address internal constant PFEc = 0xB20000000000000000000018FE7eC7d6DfeeB528;
    address internal constant PMc = 0xB2000000000000000000008FC2A8C23cf5937b66;

    // ── the 21 other stocks declared by the issuer (2026-10-03), read on chain the same day ────────────────────────
    address internal constant AMCc = 0xB200000000000000000000CD7e6b8042cb7c2BB5;
    address internal constant AEOc = 0xB2000000000000000000006064f8EC027f042294;
    address internal constant BMNRc = 0xB200000000000000000000eA2df44A307CaB279C;
    address internal constant BIRDc = 0xB200000000000000000000535fE96f18204BFD96;
    address internal constant BYNDc = 0xB200000000000000000000801830b13b8E493423;
    address internal constant CIFRc = 0xB200000000000000000000690275843B6e246286;
    address internal constant CLSKc = 0xB200000000000000000000fa63cFFF5c794dbB95;
    address internal constant CRCLc = 0xB20000000000000000000019f6E7C675b73C2e4D;
    address internal constant CRWVc = 0xB200000000000000000000F111184A74720787E6;
    address internal constant HUTc = 0xb2000000000000000000006Ee1C139a723872e09;
    address internal constant KSSc = 0xB200000000000000000000105A1f43ff3605C5De;
    address internal constant LCIDc = 0xB20000000000000000000081050Ac3d4395Df527;
    address internal constant MARAc = 0xB200000000000000000000a310e034E09186Fb2d;
    address internal constant OPENc = 0xb200000000000000000000259694B27Bf052E7d7;
    address internal constant RIOTc = 0xb200000000000000000000bd0C7627b663c581A6;
    address internal constant SOUNc = 0xB2000000000000000000002137743D4a01Fe4e88;
    address internal constant USDEc = 0xB2000000000000000000009426B660396eBCf343;
    address internal constant VVVc = 0xb200000000000000000000FEC679b39992F67627;
    address internal constant WULFc = 0xb200000000000000000000432a1d2Bd864ACEc82;
    address internal constant WWc = 0xb20000000000000000000089221e238277d52515;
    address internal constant XYZc = 0xB20000000000000000000067C8C151f24E1c9924;

    uint256 internal constant N = 62;

    uint256 internal constant PLANCHER_ETH = 375_110_845_363_267; // POOL
    uint256 internal constant PLANCHER_USDC = 1_000_000; // UNIT
    uint256 internal constant PLANCHER_CBBTC = 1_188; // POOL
    uint256 internal constant PLANCHER_TOSHI = 8_317_319_830_414_303_380_420; // POOL
    uint256 internal constant PLANCHER_OUSD = 999_999; // POOL
    uint256 internal constant PLANCHER_AAPLC = 299_602; // POOL
    uint256 internal constant PLANCHER_AMZNC = 398_718; // POOL
    uint256 internal constant PLANCHER_AVGOC = 281_034; // REFERENCE
    uint256 internal constant PLANCHER_BEC = 349_957; // POOL
    uint256 internal constant PLANCHER_GOOGLC = 291_316; // POOL
    uint256 internal constant PLANCHER_HIMSC = 3_491_206; // POOL
    uint256 internal constant PLANCHER_METAC = 137_518; // POOL
    uint256 internal constant PLANCHER_MSFTC = 194_024; // POOL
    uint256 internal constant PLANCHER_MSTRC = 620_014; // POOL
    uint256 internal constant PLANCHER_MUC = 93_187; // POOL
    uint256 internal constant PLANCHER_NVDAC = 426_462; // POOL
    uint256 internal constant PLANCHER_PLTRC = 528_421; // POOL
    uint256 internal constant PLANCHER_SNDKC = 57_696; // POOL
    uint256 internal constant PLANCHER_SPCXC = 632_956; // POOL
    uint256 internal constant PLANCHER_TSLAC = 267_254; // POOL
    uint256 internal constant PLANCHER_AMDC = 163_042; // POOL
    uint256 internal constant PLANCHER_ASTSC = 1_732_830; // POOL
    uint256 internal constant PLANCHER_CAKEC = 861_852; // POOL
    uint256 internal constant PLANCHER_DJTC = 10_899_892; // POOL
    uint256 internal constant PLANCHER_DUOLC = 667_208; // POOL
    uint256 internal constant PLANCHER_LLYC = 84_765; // POOL
    uint256 internal constant PLANCHER_MRNAC = 562_732; // POOL
    uint256 internal constant PLANCHER_MRVLC = 391_228; // POOL
    uint256 internal constant PLANCHER_NFLXC = 1_445_203; // POOL
    uint256 internal constant PLANCHER_NVAXC = 8_852_346; // POOL
    uint256 internal constant PLANCHER_ORCLC = 725_794; // POOL
    uint256 internal constant PLANCHER_PTONC = 18_498_181; // POOL
    uint256 internal constant PLANCHER_PYPLC = 1_922_034; // POOL
    uint256 internal constant PLANCHER_QUBTC = 11_530_252; // POOL
    uint256 internal constant PLANCHER_RBLXC = 2_269_118; // REFERENCE
    uint256 internal constant PLANCHER_RDDTC = 668_650; // POOL
    uint256 internal constant PLANCHER_TTWOC = 498_231; // POOL
    uint256 internal constant PLANCHER_WENC = 16_250_122; // REFERENCE
    uint256 internal constant PLANCHER_GMEC = 4_162_864; // POOL
    uint256 internal constant PLANCHER_HTZC = 57_636_888; // REFERENCE
    uint256 internal constant PLANCHER_PFEC = 3_606_203; // REFERENCE
    uint256 internal constant PLANCHER_PMC = 517_639; // POOL
    // the 21 of 2026-10-03: REFERENCE (no pool declared; Yahoo + Nasdaq agree to the cent)
    uint256 internal constant PLANCHER_AMCC = 36_101_084; // REFERENCE $2.77
    uint256 internal constant PLANCHER_AEOC = 5_646_528; // REFERENCE $17.71
    uint256 internal constant PLANCHER_BMNRC = 3_806_624; // REFERENCE $26.27
    uint256 internal constant PLANCHER_BIRDC = 29_717_683; // REFERENCE $3.365
    uint256 internal constant PLANCHER_BYNDC = 12_121_213; // REFERENCE $8.25
    uint256 internal constant PLANCHER_CIFRC = 6_365_373; // REFERENCE $15.71
    uint256 internal constant PLANCHER_CLSKC = 7_849_294; // REFERENCE $12.74
    uint256 internal constant PLANCHER_CRCLC = 1_230_770; // REFERENCE $81.25
    uint256 internal constant PLANCHER_CRWVC = 1_115_823; // REFERENCE $89.62
    uint256 internal constant PLANCHER_HUTC = 1_115_698; // REFERENCE $89.63
    uint256 internal constant PLANCHER_KSSC = 5_316_322; // REFERENCE $18.81
    uint256 internal constant PLANCHER_LCIDC = 24_213_076; // REFERENCE $4.13
    uint256 internal constant PLANCHER_MARAC = 8_904_720; // REFERENCE $11.23
    uint256 internal constant PLANCHER_OPENC = 40_983_607; // REFERENCE $2.44
    uint256 internal constant PLANCHER_RIOTC = 5_068_424; // REFERENCE $19.73
    uint256 internal constant PLANCHER_SOUNC = 17_123_288; // REFERENCE $5.84
    uint256 internal constant PLANCHER_USDEC = 7_067_138; // REFERENCE $14.15
    uint256 internal constant PLANCHER_VVVC = 3_270_112; // REFERENCE $30.58
    uint256 internal constant PLANCHER_WULFC = 6_455_778; // REFERENCE $15.49
    uint256 internal constant PLANCHER_WWC = 6_784_261; // REFERENCE $14.74
    uint256 internal constant PLANCHER_XYZC = 1_345_352; // REFERENCE $74.33

    function nouvelles() internal pure returns (address[22] memory n) {
        n = [AMDc, ASTSc, CAKEc, DJTc, DUOLc, LLYc, MRNAc, MRVLc, NFLXc, NVAXc, ORCLc, PTONc, PYPLc, QUBTc, RBLXc, RDDTc, TTWOc, WENc, GMEc, HTZc, PFEc, PMc];
    }

    /// @notice the 21 issuer stocks added on 2026-10-03 (SOUNc minted, 20 created with supply 0), appended after `nouvelles()`.
    function emetteur21() internal pure returns (address[21] memory e) {
        e = [AMCc, AEOc, BMNRc, BIRDc, BYNDc, CIFRc, CLSKc, CRCLc, CRWVc, HUTc, KSSc, LCIDc, MARAc, OPENc, RIOTc, SOUNc, USDEc, VVVc, WULFc, WWc, XYZc];
    }

    function liste() internal pure returns (address[] memory l) {
        address[] memory v9 = V9Devises.liste();
        address[22] memory n = nouvelles();
        address[21] memory e = emetteur21();
        l = new address[](N);
        for (uint256 i; i < v9.length; ++i) l[i] = v9[i];
        for (uint256 i; i < n.length; ++i) l[v9.length + i] = n[i];
        for (uint256 i; i < e.length; ++i) l[v9.length + n.length + i] = e[i];
    }

    /// @notice the raw caution floor of each currency of `liste()`, same order
    function planchers() internal pure returns (uint256[] memory p) {
        uint256[N] memory f = [PLANCHER_USDC, PLANCHER_CBBTC, PLANCHER_TOSHI, PLANCHER_OUSD, PLANCHER_AAPLC, PLANCHER_AMZNC, PLANCHER_AVGOC, PLANCHER_BEC, PLANCHER_GOOGLC, PLANCHER_HIMSC, PLANCHER_METAC, PLANCHER_MSFTC, PLANCHER_MSTRC, PLANCHER_MUC, PLANCHER_NVDAC, PLANCHER_PLTRC, PLANCHER_SNDKC, PLANCHER_SPCXC, PLANCHER_TSLAC, PLANCHER_AMDC, PLANCHER_ASTSC, PLANCHER_CAKEC, PLANCHER_DJTC, PLANCHER_DUOLC, PLANCHER_LLYC, PLANCHER_MRNAC, PLANCHER_MRVLC, PLANCHER_NFLXC, PLANCHER_NVAXC, PLANCHER_ORCLC, PLANCHER_PTONC, PLANCHER_PYPLC, PLANCHER_QUBTC, PLANCHER_RBLXC, PLANCHER_RDDTC, PLANCHER_TTWOC, PLANCHER_WENC, PLANCHER_GMEC, PLANCHER_HTZC, PLANCHER_PFEC, PLANCHER_PMC,
            PLANCHER_AMCC, PLANCHER_AEOC, PLANCHER_BMNRC, PLANCHER_BIRDC, PLANCHER_BYNDC, PLANCHER_CIFRC, PLANCHER_CLSKC, PLANCHER_CRCLC, PLANCHER_CRWVC, PLANCHER_HUTC, PLANCHER_KSSC, PLANCHER_LCIDC, PLANCHER_MARAC, PLANCHER_OPENC, PLANCHER_RIOTC, PLANCHER_SOUNC, PLANCHER_USDEC, PLANCHER_VVVC, PLANCHER_WULFC, PLANCHER_WWC, PLANCHER_XYZC];
        p = new uint256[](N);
        for (uint256 i; i < N; ++i) p[i] = f[i];
    }
}
